name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: C/C++ code linter (clang-tidy, clang-format, and cppcheck)
      uses: ArtificialAmateur/cpp-linter-action@0.01
    - name: CFML TestBox Test Runner
      uses: coldfumonkeh/cfml-testbox-action@v1
